server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.70.128
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.lyc.entity # 别名扫描包

# 阿里云短信服务配置
aliyun:
  sms:
    access-key-id:
    access-key-secret:
    endpoint: dysmsapi.aliyuncs.com

logging:
  level:
    com.lyc: debug